import { expect, test } from "bun:test"
import { convertCircuitJsonToPinoutSvg } from "lib"

const pcbSoup: any[] = [
  {
    name: "pin1",
    type: "source_port",
    pin_number: 1,
    port_hints: ["pin1", "1", "PWR"],
    source_port_id: "source_port_0",
    source_component_id: "source_component_0",
  },
  {
    name: "pin2",
    type: "source_port",
    pin_number: 2,
    port_hints: ["pin2", "2"],
    source_port_id: "source_port_1",
    source_component_id: "source_component_0",
  },
  {
    name: "pin3",
    type: "source_port",
    pin_number: 3,
    port_hints: ["pin3", "3"],
    source_port_id: "source_port_2",
    source_component_id: "source_component_0",
  },
  {
    name: "pin4",
    type: "source_port",
    pin_number: 4,
    port_hints: ["pin4", "4"],
    source_port_id: "source_port_3",
    source_component_id: "source_component_0",
  },
  {
    name: "pin5",
    type: "source_port",
    pin_number: 5,
    port_hints: ["pin5", "5"],
    source_port_id: "source_port_4",
    source_component_id: "source_component_0",
  },
  {
    name: "pin6",
    type: "source_port",
    pin_number: 6,
    port_hints: ["pin6", "6"],
    source_port_id: "source_port_5",
    source_component_id: "source_component_0",
  },
  {
    name: "pin7",
    type: "source_port",
    pin_number: 7,
    port_hints: ["pin7", "7"],
    source_port_id: "source_port_6",
    source_component_id: "source_component_0",
  },
  {
    name: "pin8",
    type: "source_port",
    pin_number: 8,
    port_hints: ["pin8", "8", "GND"],
    source_port_id: "source_port_7",
    source_component_id: "source_component_0",
  },
  {
    name: "U1",
    type: "source_component",
    ftype: "simple_chip",
    source_component_id: "source_component_0",
  },
  {
    type: "pcb_component",
    source_component_id: "source_component_0",
    pcb_component_id: "pcb_component_0",
    layer: "top",
    center: { x: 0, y: 0 },
    rotation: 0,
    width: 4.3,
    height: 3.81,
  },
  {
    type: "pcb_board",
    width: 10,
    outline: [
      { x: -10, y: -10 },
      { x: 10, y: -10 },
      { x: 10, y: 10 },
      { x: -10, y: 10 },
    ],
    center: {
      x: 0,
      y: 0,
    },
    height: 10,
    pcb_board_id: "pcb_board_0",
  },
  {
    x: -2.15,
    y: 1.905,
    type: "pcb_port",
    layers: ["top"],
    pcb_port_id: "pcb_port_0",
    source_port_id: "source_port_0",
    pcb_component_id: "pcb_component_0",
    is_board_pinout: true,
  },
  {
    x: -2.15,
    y: 0.635,
    type: "pcb_port",
    layers: ["top"],
    pcb_port_id: "pcb_port_1",
    source_port_id: "source_port_1",
    pcb_component_id: "pcb_component_0",
    is_board_pinout: true,
  },
  {
    x: -2.15,
    y: -0.635,
    type: "pcb_port",
    layers: ["top"],
    pcb_port_id: "pcb_port_2",
    source_port_id: "source_port_2",
    pcb_component_id: "pcb_component_0",
    is_board_pinout: true,
  },
  {
    x: -2.15,
    y: -1.905,
    type: "pcb_port",
    layers: ["top"],
    pcb_port_id: "pcb_port_3",
    source_port_id: "source_port_3",
    pcb_component_id: "pcb_component_0",
    is_board_pinout: true,
  },
  {
    x: 2.15,
    y: -1.905,
    type: "pcb_port",
    layers: ["top"],
    pcb_port_id: "pcb_port_4",
    source_port_id: "source_port_4",
    pcb_component_id: "pcb_component_0",
    is_board_pinout: true,
  },
  {
    x: 2.15,
    y: -0.635,
    type: "pcb_port",
    layers: ["top"],
    pcb_port_id: "pcb_port_5",
    source_port_id: "source_port_5",
    pcb_component_id: "pcb_component_0",
    is_board_pinout: true,
  },
  {
    x: 2.15,
    y: 0.635,
    type: "pcb_port",
    layers: ["top"],
    pcb_port_id: "pcb_port_6",
    source_port_id: "source_port_6",
    pcb_component_id: "pcb_component_0",
    is_board_pinout: true,
  },
  {
    x: 2.15,
    y: 1.905,
    type: "pcb_port",
    layers: ["top"],
    pcb_port_id: "pcb_port_7",
    source_port_id: "source_port_7",
    pcb_component_id: "pcb_component_0",
    is_board_pinout: true,
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: -2.15,
    y: 1.905,
    width: 0.6,
    height: 1,
    layer: "top",
    pcb_port_id: "pcb_port_0",
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: -2.15,
    y: 0.635,
    width: 0.6,
    height: 1,
    layer: "top",
    pcb_port_id: "pcb_port_1",
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: -2.15,
    y: -0.635,
    width: 0.6,
    height: 1,
    layer: "top",
    pcb_port_id: "pcb_port_2",
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: -2.15,
    y: -1.905,
    width: 0.6,
    height: 1,
    layer: "top",
    pcb_port_id: "pcb_port_3",
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: 2.15,
    y: -1.905,
    width: 0.6,
    height: 1,
    layer: "top",
    pcb_port_id: "pcb_port_4",
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: 2.15,
    y: -0.635,
    width: 0.6,
    height: 1,
    layer: "top",
    pcb_port_id: "pcb_port_5",
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: 2.15,
    y: 0.635,
    width: 0.6,
    height: 1,
    layer: "top",
    pcb_port_id: "pcb_port_6",
  },
  {
    type: "pcb_smtpad",
    shape: "rect",
    x: 2.15,
    y: 1.905,
    width: 0.6,
    height: 1,
    layer: "top",
    pcb_port_id: "pcb_port_7",
  },
]

test("Pinout with complex board", () => {
  expect(convertCircuitJsonToPinoutSvg(pcbSoup)).toMatchSvgSnapshot(
    import.meta.path,
  )
})
