import { expect, test } from "bun:test"
import type { AnyCircuitElement } from "circuit-json"
import { convertCircuitJsonToPcbSvg } from "lib"

test("mixed small and large components compact layout shows sensible anchor offsets", () => {
  const circuitJson = [
    {
      type: "pcb_board",
      pcb_board_id: "board_1",
      center: { x: 0, y: 0 },
      width: 60,
      height: 40,
      num_layers: 2,
      material: "fr4",
      thickness: 1.6,
    },

    // A dense cluster of mixed-size components placed compactly (manually specified)
    // big components
    {
      type: "pcb_component",
      pcb_component_id: "c_big_1",
      source_component_id: "big_1",
      center: { x: 8, y: 6 },
      width: 12,
      height: 10,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "8mm",
      display_offset_y: "6mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_big_2",
      source_component_id: "big_2",
      center: { x: -10, y: -6 },
      width: 14,
      height: 10,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "-10mm",
      display_offset_y: "-6mm",
    },

    // medium components
    {
      type: "pcb_component",
      pcb_component_id: "c_med_1",
      source_component_id: "med_1",
      center: { x: -6, y: 3 },
      width: 6,
      height: 4,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "-6mm",
      display_offset_y: "3mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_med_2",
      source_component_id: "med_2",
      center: { x: 6, y: -4 },
      width: 5,
      height: 3,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "6mm",
      display_offset_y: "-4mm",
    },

    // many small/tiny components packed tightly around the mediums and bigs
    {
      type: "pcb_component",
      pcb_component_id: "c_s_01",
      source_component_id: "s01",
      center: { x: -2, y: 6 },
      width: 2,
      height: 1.5,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "-2mm",
      display_offset_y: "6mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_s_02",
      source_component_id: "s02",
      center: { x: 2, y: 6 },
      width: 2,
      height: 1.5,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "2mm",
      display_offset_y: "6mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_t_01",
      source_component_id: "t01",
      center: { x: 0, y: 4 },
      width: 0.8,
      height: 0.8,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "0mm",
      display_offset_y: "4mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_t_02",
      source_component_id: "t02",
      center: { x: 3, y: 4 },
      width: 0.6,
      height: 0.6,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "3mm",
      display_offset_y: "4mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_t_03",
      source_component_id: "t03",
      center: { x: -3, y: 4 },
      width: 0.6,
      height: 0.6,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "-3mm",
      display_offset_y: "4mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_s_03",
      source_component_id: "s03",
      center: { x: -4, y: 0 },
      width: 2,
      height: 2,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "-4mm",
      display_offset_y: "0mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_s_04",
      source_component_id: "s04",
      center: { x: -2, y: -1 },
      width: 1.5,
      height: 1.5,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "-2mm",
      display_offset_y: "-1mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_s_05",
      source_component_id: "s05",
      center: { x: 0, y: -1 },
      width: 1.2,
      height: 1.2,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "0mm",
      display_offset_y: "-1mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_t_04",
      source_component_id: "t04",
      center: { x: 2, y: -1 },
      width: 0.7,
      height: 0.7,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "2mm",
      display_offset_y: "-1mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_t_05",
      source_component_id: "t05",
      center: { x: 4, y: -1 },
      width: 0.6,
      height: 0.6,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "4mm",
      display_offset_y: "-1mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_s_06",
      source_component_id: "s06",
      center: { x: 6, y: 0 },
      width: 2.5,
      height: 1.8,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "6mm",
      display_offset_y: "0mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_s_07",
      source_component_id: "s07",
      center: { x: 8, y: 2 },
      width: 2,
      height: 1.6,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "8mm",
      display_offset_y: "2mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_t_06",
      source_component_id: "t06",
      center: { x: -8, y: -2 },
      width: 0.9,
      height: 0.9,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "-8mm",
      display_offset_y: "-2mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_s_08",
      source_component_id: "s08",
      center: { x: -6, y: -4 },
      width: 1.8,
      height: 1.2,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "-6mm",
      display_offset_y: "-4mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_t_07",
      source_component_id: "t07",
      center: { x: -4, y: -4 },
      width: 0.6,
      height: 0.6,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "-4mm",
      display_offset_y: "-4mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_s_09",
      source_component_id: "s09",
      center: { x: -2, y: -4 },
      width: 1.6,
      height: 1.6,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "-2mm",
      display_offset_y: "-4mm",
    },
    {
      type: "pcb_component",
      pcb_component_id: "c_t_08",
      source_component_id: "t08",
      center: { x: 0, y: -4 },
      width: 0.6,
      height: 0.6,
      layer: "top",
      rotation: 0,
      position_mode: "relative_to_group_anchor",
      positioned_relative_to_pcb_board_id: "board_1",
      display_offset_x: "0mm",
      display_offset_y: "-4mm",
    },
  ] as AnyCircuitElement[]

  const svg = convertCircuitJsonToPcbSvg(circuitJson, {
    showAnchorOffsets: true,
    colorOverrides: {
      debugComponent: {
        fill: "rgba(255, 0, 0, 0.06)",
        stroke: "red",
      },
    },
  })

  expect(svg).toMatchSvgSnapshot(
    import.meta.path,
    "mixed-size-components-compact",
  )
})
