import type { AnyCircuitElement, PcbBoard, PcbVia } from "circuit-json"

const board: PcbBoard = {
  type: "pcb_board",
  pcb_board_id: "unplugged",
  subcircuit_id: "unplugged",
  center: { x: -5, y: 0 },
  width: 9,
  height: 8,
  thickness: 1.6,
  num_layers: 2,
  material: "fr4",
  min_via_hole_diameter: 1,
  min_via_pad_diameter: 2,
  default_via_tented_on_top: true,
  default_via_tented_on_bottom: false,
}

const via: PcbVia = {
  type: "pcb_via",
  pcb_via_id: "inherited",
  subcircuit_id: "unplugged",
  x: -7,
  y: 1.5,
  outer_diameter: 2,
  hole_diameter: 1,
  layers: ["top", "bottom"],
}

export const circuit: AnyCircuitElement[] = [
  board,
  {
    ...board,
    pcb_board_id: "plugged",
    subcircuit_id: "plugged",
    center: { x: 5, y: 0 },
    default_via_plugged: true,
  },
  via,
  {
    ...via,
    pcb_via_id: "override",
    x: -3,
    tented_on_top: false,
    tented_on_bottom: true,
  },
  {
    ...via,
    pcb_via_id: "pad_overlap",
    x: -3,
    y: -1.5,
    tented_on_bottom: true,
  },
  {
    ...via,
    pcb_via_id: "plugged_inherited",
    subcircuit_id: "plugged",
    x: 3,
  },
  {
    ...via,
    pcb_via_id: "plugged_override",
    subcircuit_id: "plugged",
    x: 7,
    tented_on_top: false,
    tented_on_bottom: true,
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "unplugged_route",
    subcircuit_id: "unplugged",
    route: [
      { route_type: "wire", x: -8.5, y: -1.5, layer: "top", width: 0.3 },
      { route_type: "wire", x: -7, y: -1.5, layer: "top", width: 0.3 },
      {
        route_type: "via",
        x: -7,
        y: -1.5,
        from_layer: "top",
        to_layer: "bottom",
        hole_diameter: 1,
        outer_diameter: 2,
        tented_on_bottom: true,
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "plugged_route",
    subcircuit_id: "plugged",
    route: [
      { route_type: "wire", x: 1.5, y: -1.5, layer: "top", width: 0.3 },
      { route_type: "wire", x: 3, y: -1.5, layer: "top", width: 0.3 },
      {
        route_type: "via",
        x: 3,
        y: -1.5,
        from_layer: "top",
        to_layer: "bottom",
        hole_diameter: 1,
        outer_diameter: 2,
        tented_on_bottom: true,
      },
    ],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "top_pad",
    pcb_component_id: "component",
    subcircuit_id: "unplugged",
    shape: "rect",
    x: -3.6,
    y: -1.5,
    width: 1.2,
    height: 2,
    layer: "top",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "bottom_pad",
    pcb_component_id: "component",
    subcircuit_id: "unplugged",
    shape: "rect",
    x: -3.6,
    y: -1.5,
    width: 1.2,
    height: 2,
    layer: "bottom",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "unplugged_title",
    pcb_component_id: "component",
    subcircuit_id: "unplugged",
    anchor_position: { x: -5, y: 3.2 },
    anchor_alignment: "center",
    layer: "top",
    font: "tscircuit2024",
    font_size: 0.6,
    text: "UNPLUGGED",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "plugged_title",
    pcb_component_id: "component",
    subcircuit_id: "plugged",
    anchor_position: { x: 5, y: 3.2 },
    anchor_alignment: "center",
    layer: "top",
    font: "tscircuit2024",
    font_size: 0.6,
    text: "PLUGGED",
  },
]
