import type { AnyCircuitElement, PcbVia } from "circuit-json"

const via: PcbVia = {
  type: "pcb_via",
  pcb_via_id: "inherited",
  subcircuit_id: "board",
  x: -2,
  y: 1.5,
  outer_diameter: 2,
  hole_diameter: 1,
  layers: ["top", "bottom"],
}

export const circuit: AnyCircuitElement[] = [
  {
    type: "pcb_board",
    pcb_board_id: "board",
    subcircuit_id: "board",
    center: { x: 0, y: 0 },
    width: 9,
    height: 8,
    thickness: 1.6,
    num_layers: 2,
    material: "fr4",
    min_via_hole_diameter: 1,
    min_via_pad_diameter: 2,
    default_via_tented_on_top: true,
    default_via_tented_on_bottom: false,
  },
  via,
  {
    ...via,
    pcb_via_id: "override",
    x: 2,
    tented_on_top: false,
    tented_on_bottom: true,
  },
  {
    ...via,
    pcb_via_id: "pad_overlap",
    x: 2,
    y: -1.5,
    tented_on_bottom: true,
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "route_via",
    subcircuit_id: "board",
    route: [
      { route_type: "wire", x: -3.5, y: -1.5, layer: "top", width: 0.3 },
      { route_type: "wire", x: -2, y: -1.5, layer: "top", width: 0.3 },
      {
        route_type: "via",
        x: -2,
        y: -1.5,
        from_layer: "top",
        to_layer: "bottom",
        hole_diameter: 1,
        outer_diameter: 2,
        tented_on_bottom: true,
      },
    ],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "top_pad",
    pcb_component_id: "component",
    subcircuit_id: "board",
    shape: "rect",
    x: 1.4,
    y: -1.5,
    width: 1.2,
    height: 2,
    layer: "top",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "bottom_pad",
    pcb_component_id: "component",
    subcircuit_id: "board",
    shape: "rect",
    x: 1.4,
    y: -1.5,
    width: 1.2,
    height: 2,
    layer: "bottom",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "top_title",
    pcb_component_id: "component",
    subcircuit_id: "board",
    anchor_position: { x: 0, y: 3.2 },
    anchor_alignment: "center",
    layer: "top",
    font: "tscircuit2024",
    font_size: 0.6,
    text: "VIA TENTING",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "bottom_title",
    pcb_component_id: "component",
    subcircuit_id: "board",
    anchor_position: { x: 0, y: 3.2 },
    anchor_alignment: "center",
    layer: "bottom",
    font: "tscircuit2024",
    font_size: 0.6,
    text: "VIA TENTING",
  },
]
