import type { AnyCircuitElement, PcbNoteText } from "circuit-json"

export const viaTentingViewLabel: Omit<PcbNoteText, "text"> = {
  type: "pcb_note_text",
  pcb_note_text_id: "view_label",
  anchor_position: { x: 0, y: 6 },
  anchor_alignment: "center",
  layer: "top",
  font: "tscircuit2024",
  font_size: 1,
  color: "#ffffff",
}

export const viaTentingCircuit: AnyCircuitElement[] = [
  {
    type: "pcb_board",
    pcb_board_id: "board",
    center: { x: 0, y: 0 },
    width: 60,
    height: 16,
    num_layers: 2,
    thickness: 1.6,
    material: "fr4",
  },
  {
    type: "pcb_via",
    pcb_via_id: "via_0",
    x: -24,
    y: 0,
    outer_diameter: 2.4,
    hole_diameter: 1.2,
    layers: ["top", "bottom"],
    tented_on_top: false,
    tented_on_bottom: false,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "label_0",
    text: "Exposed",
    anchor_position: { x: -24, y: 2.8 },
    anchor_alignment: "center",
    layer: "top",
    font: "tscircuit2024",
    font_size: 0.8,
    color: "#ffffff",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "trace_0_top",
    route: [
      { route_type: "wire", x: -27, y: -2, width: 0.4, layer: "top" },
      { route_type: "wire", x: -24, y: 0, width: 0.4, layer: "top" },
      {
        route_type: "via",
        x: -24,
        y: 0,
        from_layer: "top",
        to_layer: "bottom",
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "trace_0_bottom",
    route: [
      { route_type: "wire", x: -27, y: -2, width: 0.4, layer: "bottom" },
      { route_type: "wire", x: -24, y: 0, width: 0.4, layer: "bottom" },
      {
        route_type: "via",
        x: -24,
        y: 0,
        from_layer: "top",
        to_layer: "bottom",
      },
    ],
  },
  {
    type: "pcb_via",
    pcb_via_id: "via_1",
    x: -12,
    y: 0,
    outer_diameter: 2.4,
    hole_diameter: 1.2,
    layers: ["top", "bottom"],
    tented_on_top: true,
    tented_on_bottom: false,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "label_1",
    text: "Top tented",
    anchor_position: { x: -12, y: 2.8 },
    anchor_alignment: "center",
    layer: "top",
    font: "tscircuit2024",
    font_size: 0.8,
    color: "#ffffff",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "trace_1_top",
    route: [
      { route_type: "wire", x: -15, y: -2, width: 0.4, layer: "top" },
      { route_type: "wire", x: -12, y: 0, width: 0.4, layer: "top" },
      {
        route_type: "via",
        x: -12,
        y: 0,
        from_layer: "top",
        to_layer: "bottom",
      },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "trace_1_bottom",
    route: [
      { route_type: "wire", x: -15, y: -2, width: 0.4, layer: "bottom" },
      { route_type: "wire", x: -12, y: 0, width: 0.4, layer: "bottom" },
      {
        route_type: "via",
        x: -12,
        y: 0,
        from_layer: "top",
        to_layer: "bottom",
      },
    ],
  },
  {
    type: "pcb_via",
    pcb_via_id: "via_2",
    x: 0,
    y: 0,
    outer_diameter: 2.4,
    hole_diameter: 1.2,
    layers: ["top", "bottom"],
    tented_on_top: false,
    tented_on_bottom: true,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "label_2",
    text: "Bottom tented",
    anchor_position: { x: 0, y: 2.8 },
    anchor_alignment: "center",
    layer: "top",
    font: "tscircuit2024",
    font_size: 0.8,
    color: "#ffffff",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "trace_2_top",
    route: [
      { route_type: "wire", x: -3, y: -2, width: 0.4, layer: "top" },
      { route_type: "wire", x: 0, y: 0, width: 0.4, layer: "top" },
      { route_type: "via", x: 0, y: 0, from_layer: "top", to_layer: "bottom" },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "trace_2_bottom",
    route: [
      { route_type: "wire", x: -3, y: -2, width: 0.4, layer: "bottom" },
      { route_type: "wire", x: 0, y: 0, width: 0.4, layer: "bottom" },
      { route_type: "via", x: 0, y: 0, from_layer: "top", to_layer: "bottom" },
    ],
  },
  {
    type: "pcb_via",
    pcb_via_id: "via_3",
    x: 12,
    y: 0,
    outer_diameter: 2.4,
    hole_diameter: 1.2,
    layers: ["top", "bottom"],
    tented_on_top: true,
    tented_on_bottom: true,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "label_3",
    text: "Both tented",
    anchor_position: { x: 12, y: 2.8 },
    anchor_alignment: "center",
    layer: "top",
    font: "tscircuit2024",
    font_size: 0.8,
    color: "#ffffff",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "trace_3_top",
    route: [
      { route_type: "wire", x: 9, y: -2, width: 0.4, layer: "top" },
      { route_type: "wire", x: 12, y: 0, width: 0.4, layer: "top" },
      { route_type: "via", x: 12, y: 0, from_layer: "top", to_layer: "bottom" },
    ],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "trace_3_bottom",
    route: [
      { route_type: "wire", x: 9, y: -2, width: 0.4, layer: "bottom" },
      { route_type: "wire", x: 12, y: 0, width: 0.4, layer: "bottom" },
      { route_type: "via", x: 12, y: 0, from_layer: "top", to_layer: "bottom" },
    ],
  },
  {
    type: "pcb_plated_hole",
    pcb_plated_hole_id: "connector",
    shape: "circle",
    x: 24,
    y: 0,
    outer_diameter: 3.6,
    hole_diameter: 1.8,
    layers: ["top", "bottom"],
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "connector_label",
    text: "Connector",
    anchor_position: { x: 24, y: 2.8 },
    anchor_alignment: "center",
    layer: "top",
    font: "tscircuit2024",
    font_size: 0.8,
    color: "#ffffff",
  },
]
