import { test, expect } from "bun:test"
import { convertCircuitJsonToPcbSvg } from "lib"

test("multiple pcb_groups with different sized components", () => {
  const circuitJson = [
    {
      type: "pcb_board",
      pcb_board_id: "board_1",
      center: { x: 0, y: 0 },
      width: 80,
      height: 60,
      num_layers: 2,
      material: "fr4",
      thickness: 1.6,
    },
    // Group 1: Top-left with small components
    {
      type: "pcb_group",
      pcb_group_id: "group_1",
      source_group_id: "source_group_1",
      name: "Group 1",
      center: { x: -20, y: 15 },
      width: 12,
      height: 10,
      pcb_component_ids: ["comp_1", "comp_2"],
    },
    {
      type: "pcb_component",
      pcb_component_id: "comp_1",
      source_component_id: "source_1",
      center: { x: -3, y: 2 },
      width: 3,
      height: 2,
      layer: "top",
      rotation: 0,
      positioned_relative_to_pcb_group_id: "group_1",
      position_mode: "relative",
    },
    {
      type: "pcb_component",
      pcb_component_id: "comp_2",
      source_component_id: "source_2",
      center: { x: 2, y: -3 },
      width: 2.5,
      height: 2,
      layer: "top",
      rotation: 0,
      positioned_relative_to_pcb_group_id: "group_1",
      position_mode: "relative",
    },
    // Group 2: Top-right with medium components
    {
      type: "pcb_group",
      pcb_group_id: "group_2",
      source_group_id: "source_group_2",
      name: "Group 2",
      center: { x: 20, y: 15 },
      width: 15,
      height: 12,
      pcb_component_ids: ["comp_3", "comp_4"],
    },
    {
      type: "pcb_component",
      pcb_component_id: "comp_3",
      source_component_id: "source_3",
      center: { x: 4, y: -2 },
      width: 5,
      height: 3,
      layer: "top",
      rotation: 0,
      positioned_relative_to_pcb_group_id: "group_2",
      position_mode: "relative",
    },
    {
      type: "pcb_component",
      pcb_component_id: "comp_4",
      source_component_id: "source_4",
      center: { x: -3, y: 3 },
      width: 4,
      height: 3.5,
      layer: "top",
      rotation: 0,
      positioned_relative_to_pcb_group_id: "group_2",
      position_mode: "relative",
    },
    // Group 3: Bottom-left with large components
    {
      type: "pcb_group",
      pcb_group_id: "group_3",
      source_group_id: "source_group_3",
      name: "Group 3",
      center: { x: -20, y: -15 },
      width: 18,
      height: 14,
      pcb_component_ids: ["comp_5", "comp_6"],
    },
    {
      type: "pcb_component",
      pcb_component_id: "comp_5",
      source_component_id: "source_5",
      center: { x: -4, y: -3 },
      width: 6,
      height: 5,
      layer: "top",
      rotation: 0,
      positioned_relative_to_pcb_group_id: "group_3",
      position_mode: "relative",
    },
    {
      type: "pcb_component",
      pcb_component_id: "comp_6",
      source_component_id: "source_6",
      center: { x: 3, y: 4 },
      width: 5,
      height: 4,
      layer: "top",
      rotation: 0,
      positioned_relative_to_pcb_group_id: "group_3",
      position_mode: "relative",
    },
    // Group 4: Bottom-right with varied components
    {
      type: "pcb_group",
      pcb_group_id: "group_4",
      source_group_id: "source_group_4",
      name: "Group 4",
      center: { x: 20, y: -15 },
      width: 16,
      height: 13,
      pcb_component_ids: ["comp_7", "comp_8"],
    },
    {
      type: "pcb_component",
      pcb_component_id: "comp_7",
      source_component_id: "source_7",
      center: { x: 5, y: 2 },
      width: 4,
      height: 6,
      layer: "top",
      rotation: 0,
      positioned_relative_to_pcb_group_id: "group_4",
      position_mode: "relative",
    },
    {
      type: "pcb_component",
      pcb_component_id: "comp_8",
      source_component_id: "source_8",
      center: { x: -4, y: -3 },
      width: 3,
      height: 3,
      layer: "top",
      rotation: 0,
      positioned_relative_to_pcb_group_id: "group_4",
      position_mode: "relative",
    },
  ] as any

  const svg = convertCircuitJsonToPcbSvg(circuitJson, {
    showPcbGroups: true,
    showAnchorOffsets: true,
    colorOverrides: {
      debugComponent: {
        fill: "rgba(255, 0, 0, 0.1)",
        stroke: "red",
      },
    },
  })

  expect(svg).toMatchSvgSnapshot(import.meta.path)
})
