import { test, expect } from "bun:test"
import { convertCircuitJsonToPcbSvg } from "lib"

const createAnchorMarker = (id: string, x: number, y: number) => [
  {
    type: "pcb_silkscreen_line" as const,
    layer: "top" as const,
    pcb_component_id: "pcb_anchor_marker",
    pcb_silkscreen_line_id: `anchor_marker_h_${id}`,
    x1: x - 0.45,
    y1: y,
    x2: x + 0.45,
    y2: y,
    stroke_width: 0.1,
  },
  {
    type: "pcb_silkscreen_line" as const,
    layer: "top" as const,
    pcb_component_id: "pcb_anchor_marker",
    pcb_silkscreen_line_id: `anchor_marker_v_${id}`,
    x1: x,
    y1: y - 0.45,
    x2: x,
    y2: y + 0.45,
    stroke_width: 0.1,
  },
  {
    type: "pcb_silkscreen_circle" as const,
    layer: "top" as const,
    pcb_component_id: "pcb_anchor_marker",
    pcb_silkscreen_circle_id: `anchor_marker_dot_${id}`,
    center: { x, y },
    radius: 0.14,
    stroke_width: 0.08,
    is_filled: true,
  },
]

test("silkscreen knockout text honors anchor alignment", () => {
  const svg = convertCircuitJsonToPcbSvg([
    {
      type: "pcb_board",
      pcb_board_id: "pcb_board_0",
      width: 28,
      height: 20,
      center: { x: 0, y: 0 },
      num_layers: 2,
      material: "fr4",
      thickness: 1.2,
    },
    {
      type: "pcb_silkscreen_text",
      layer: "top",
      pcb_silkscreen_text_id: "pcb_silkscreen_text_top_left",
      font: "tscircuit2024",
      font_size: 1,
      pcb_component_id: "pcb_generic_component_0",
      anchor_position: { x: -7, y: 5 },
      anchor_alignment: "top_left",
      text: "TL",
      is_knockout: true,
    },
    {
      type: "pcb_silkscreen_text",
      layer: "top",
      pcb_silkscreen_text_id: "pcb_silkscreen_text_bottom_right",
      font: "tscircuit2024",
      font_size: 1,
      pcb_component_id: "pcb_generic_component_0",
      anchor_position: { x: -7, y: 5 },
      anchor_alignment: "bottom_right",
      text: "BR",
      is_knockout: true,
    },
    {
      type: "pcb_silkscreen_text",
      layer: "top",
      pcb_silkscreen_text_id: "pcb_silkscreen_text_top_right",
      font: "tscircuit2024",
      font_size: 1,
      pcb_component_id: "pcb_generic_component_0",
      anchor_position: { x: 0, y: 0 },
      anchor_alignment: "top_right",
      text: "TR",
      is_knockout: true,
    },
    {
      type: "pcb_silkscreen_text",
      layer: "top",
      pcb_silkscreen_text_id: "pcb_silkscreen_text_bottom_left",
      font: "tscircuit2024",
      font_size: 1,
      pcb_component_id: "pcb_generic_component_0",
      anchor_position: { x: 0, y: 0 },
      anchor_alignment: "bottom_left",
      text: "BL",
      is_knockout: true,
    },
    {
      type: "pcb_silkscreen_text",
      layer: "top",
      pcb_silkscreen_text_id: "pcb_silkscreen_text_top_center",
      font: "tscircuit2024",
      font_size: 1,
      pcb_component_id: "pcb_generic_component_0",
      anchor_position: { x: 7, y: -6 },
      anchor_alignment: "top_center",
      text: "TC",
      is_knockout: true,
    },
    {
      type: "pcb_silkscreen_text",
      layer: "top",
      pcb_silkscreen_text_id: "pcb_silkscreen_text_bottom_center",
      font: "tscircuit2024",
      font_size: 1,
      pcb_component_id: "pcb_generic_component_0",
      anchor_position: { x: 7, y: -4 },
      anchor_alignment: "bottom_center",
      text: "BC",
      is_knockout: true,
    },
    {
      type: "pcb_silkscreen_text",
      layer: "top",
      pcb_silkscreen_text_id: "pcb_silkscreen_text_center",
      font: "tscircuit2024",
      font_size: 1,
      pcb_component_id: "pcb_generic_component_0",
      anchor_position: { x: 7, y: -5 },
      anchor_alignment: "center",
      text: "C",
      is_knockout: true,
    },
    ...createAnchorMarker("top_left_bottom_right", -7, 5),
    ...createAnchorMarker("top_right_bottom_left", 0, 0),
    ...createAnchorMarker("top_center_bottom_center_center", 7, -5),
  ])

  expect(svg).toMatchSvgSnapshot(
    import.meta.path,
    "silkscreen-knockout-anchor-alignment",
  )
})
