import type { AnyCircuitElement } from "circuit-json"

export const circuit: AnyCircuitElement[] = [
  {
    type: "pcb_board",
    pcb_board_id: "board",
    center: {
      x: 0,
      y: 0,
    },
    width: 12,
    height: 5,
    thickness: 1.6,
    num_layers: 2,
    material: "fr4",
    default_via_tented_on_top: true,
    default_via_tented_on_bottom: false,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "title",
    text: "Board defaults: top: true, bottom: false",
    anchor_position: {
      x: 0,
      y: 2,
    },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.3,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "tented_label",
    text: "top: true\nbottom: true",
    anchor_position: {
      x: -3,
      y: 1.1,
    },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.28,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "exposed_label",
    text: "top: false\nbottom: false",
    anchor_position: {
      x: 0,
      y: 1.1,
    },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.28,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "inherited_label",
    text: "top: unset\nbottom: unset",
    anchor_position: {
      x: 3,
      y: 1.1,
    },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.28,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "legend",
    text: "White silkscreen crosses tented vias; exposed vias interrupt it",
    anchor_position: {
      x: 0,
      y: -1.4,
    },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.28,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_via",
    pcb_via_id: "tented",
    x: -3,
    y: 0,
    outer_diameter: 1.4,
    hole_diameter: 0.7,
    layers: ["top", "bottom"],
    tented_on_top: true,
    tented_on_bottom: true,
  },
  {
    type: "pcb_via",
    pcb_via_id: "exposed",
    x: 0,
    y: 0,
    outer_diameter: 1.4,
    hole_diameter: 0.7,
    layers: ["top", "bottom"],
    tented_on_top: false,
    tented_on_bottom: false,
  },
  {
    type: "pcb_via",
    pcb_via_id: "inherited",
    x: 3,
    y: 0,
    outer_diameter: 1.4,
    hole_diameter: 0.7,
    layers: ["top", "bottom"],
  },
  {
    type: "pcb_silkscreen_line",
    pcb_silkscreen_line_id: "top_line",
    pcb_component_id: "component",
    x1: -4.2,
    y1: 0,
    x2: 4.2,
    y2: 0,
    stroke_width: 0.15,
    layer: "top",
  },
  {
    type: "pcb_silkscreen_line",
    pcb_silkscreen_line_id: "bottom_line",
    pcb_component_id: "component",
    x1: -4.2,
    y1: 0,
    x2: 4.2,
    y2: 0,
    stroke_width: 0.15,
    layer: "bottom",
  },
]
