import type { AnyCircuitElement } from "circuit-json"

export const circuit: AnyCircuitElement[] = [
  {
    type: "pcb_note_text",
    pcb_note_text_id: "view",
    text: "TOP VIEW - showSolderMask: true",
    anchor_position: { x: 0, y: 7.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "tenting",
    text: "All vias: tented_on_top: unset; tented_on_bottom: unset",
    anchor_position: { x: 0, y: 6.6 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.38,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_board",
    pcb_board_id: "board_plugged",
    subcircuit_id: "board_plugged",
    center: { x: -8, y: 0 },
    width: 15,
    height: 12,
    thickness: 1.6,
    num_layers: 2,
    material: "fr4",
    min_via_hole_diameter: 1.2,
    min_via_pad_diameter: 2.2,
    default_via_plugged: true,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_setting",
    text: "pcb_board\ndefault_via_plugged: true",
    anchor_position: { x: -8, y: 4.8 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.46,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_standalone",
    text: "Standalone pcb_via",
    anchor_position: { x: -8, y: 3.1 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_via",
    pcb_via_id: "board_plugged_via",
    subcircuit_id: "board_plugged",
    x: -8,
    y: 1.7,
    outer_diameter: 2.2,
    hole_diameter: 1.2,
    layers: ["top", "bottom"],
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_standalone_expected",
    text: "Expect: plugged hole, exposed copper ring",
    anchor_position: { x: -8, y: 0.1 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.35,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_route",
    text: "pcb_trace.route via",
    anchor_position: { x: -8, y: -1.2 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "board_plugged_trace",
    subcircuit_id: "board_plugged",
    route: [
      {
        route_type: "wire",
        x: -10.5,
        y: -2.7,
        width: 0.3,
        layer: "top",
      },
      {
        route_type: "wire",
        x: -8,
        y: -2.7,
        width: 0.3,
        layer: "top",
      },
      {
        route_type: "via",
        x: -8,
        y: -2.7,
        from_layer: "top",
        to_layer: "bottom",
      },
      {
        route_type: "wire",
        x: -8,
        y: -2.7,
        width: 0.3,
        layer: "bottom",
      },
      {
        route_type: "wire",
        x: -5.5,
        y: -2.7,
        width: 0.3,
        layer: "bottom",
      },
    ],
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_route_expected",
    text: "Expect: plugged hole, exposed copper ring",
    anchor_position: { x: -8, y: -4.3 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.35,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_legend",
    text: "Tan: plugging material",
    anchor_position: { x: -8, y: -5.2 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.35,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_board",
    pcb_board_id: "board_open",
    subcircuit_id: "board_open",
    center: { x: 8, y: 0 },
    width: 15,
    height: 12,
    thickness: 1.6,
    num_layers: 2,
    material: "fr4",
    min_via_hole_diameter: 1.2,
    min_via_pad_diameter: 2.2,
    default_via_plugged: false,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_setting",
    text: "pcb_board\ndefault_via_plugged: false",
    anchor_position: { x: 8, y: 4.8 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.46,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_standalone",
    text: "Standalone pcb_via",
    anchor_position: { x: 8, y: 3.1 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_via",
    pcb_via_id: "board_open_via",
    subcircuit_id: "board_open",
    x: 8,
    y: 1.7,
    outer_diameter: 2.2,
    hole_diameter: 1.2,
    layers: ["top", "bottom"],
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_standalone_expected",
    text: "Expect: open hole, exposed copper ring",
    anchor_position: { x: 8, y: 0.1 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.35,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_route",
    text: "pcb_trace.route via",
    anchor_position: { x: 8, y: -1.2 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "board_open_trace",
    subcircuit_id: "board_open",
    route: [
      {
        route_type: "wire",
        x: 5.5,
        y: -2.7,
        width: 0.3,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 8,
        y: -2.7,
        width: 0.3,
        layer: "top",
      },
      {
        route_type: "via",
        x: 8,
        y: -2.7,
        from_layer: "top",
        to_layer: "bottom",
      },
      {
        route_type: "wire",
        x: 8,
        y: -2.7,
        width: 0.3,
        layer: "bottom",
      },
      {
        route_type: "wire",
        x: 10.5,
        y: -2.7,
        width: 0.3,
        layer: "bottom",
      },
    ],
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_route_expected",
    text: "Expect: open hole, exposed copper ring",
    anchor_position: { x: 8, y: -4.3 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.35,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_legend",
    text: "Pink: open drill",
    anchor_position: { x: 8, y: -5.2 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.35,
    layer: "top",
    color: "white",
  },
]
