import type { AnyCircuitElement } from "circuit-json"

export const circuit: AnyCircuitElement[] = [
  {
    type: "pcb_note_text",
    pcb_note_text_id: "view",
    text: "TOP VIEW - showSolderMask: true",
    anchor_position: { x: 0.0, y: 1.875 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.125,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "tenting",
    text: "hole_diameter: 0.3 mm; tented_on_top: unset; tented_on_bottom: unset",
    anchor_position: { x: 0.0, y: 1.65 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.085,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_board",
    pcb_board_id: "board_plugged",
    subcircuit_id: "board_plugged",
    center: { x: -2.0, y: 0.0 },
    width: 3.75,
    height: 3.0,
    thickness: 1.6,
    num_layers: 2,
    material: "fr4",
    min_via_hole_diameter: 0.3,
    min_via_pad_diameter: 0.55,
    default_via_plugged: true,
    default_via_tented_on_top: true,
    default_via_tented_on_bottom: true,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_setting",
    text: "pcb_board\ndefault_via_plugged: true\ndefault_via_tented_on_top: true\ndefault_via_tented_on_bottom: true",
    anchor_position: { x: -2.0, y: 1.2 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.1,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_standalone",
    text: "Standalone pcb_via",
    anchor_position: { x: -2.0, y: 0.775 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.1,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_via",
    pcb_via_id: "board_plugged_via",
    subcircuit_id: "board_plugged",
    x: -2.0,
    y: 0.425,
    outer_diameter: 0.55,
    hole_diameter: 0.3,
    layers: ["top", "bottom"],
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_standalone_expected",
    text: "Expect: closed, masked via",
    anchor_position: { x: -2.0, y: 0.025 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.0875,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_route",
    text: "pcb_trace.route via",
    anchor_position: { x: -2.0, y: -0.3 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.1,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "board_plugged_trace",
    subcircuit_id: "board_plugged",
    route: [
      {
        route_type: "wire",
        x: -2.625,
        y: -0.675,
        width: 0.075,
        layer: "top",
      },
      {
        route_type: "wire",
        x: -2.0,
        y: -0.675,
        width: 0.075,
        layer: "top",
      },
      {
        route_type: "via",
        x: -2.0,
        y: -0.675,
        from_layer: "top",
        to_layer: "bottom",
      },
      {
        route_type: "wire",
        x: -2.0,
        y: -0.675,
        width: 0.075,
        layer: "bottom",
      },
      {
        route_type: "wire",
        x: -1.375,
        y: -0.675,
        width: 0.075,
        layer: "bottom",
      },
    ],
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_route_expected",
    text: "Expect: closed, masked via",
    anchor_position: { x: -2.0, y: -1.075 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.0875,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_plugged_legend",
    text: "Ink plugged + tented (JLCPCB-style)",
    anchor_position: { x: -2.0, y: -1.3 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.08,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_board",
    pcb_board_id: "board_open",
    subcircuit_id: "board_open",
    center: { x: 2.0, y: 0.0 },
    width: 3.75,
    height: 3.0,
    thickness: 1.6,
    num_layers: 2,
    material: "fr4",
    min_via_hole_diameter: 0.3,
    min_via_pad_diameter: 0.55,
    default_via_plugged: false,
    default_via_tented_on_top: false,
    default_via_tented_on_bottom: false,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_setting",
    text: "pcb_board\ndefault_via_plugged: false\ndefault_via_tented_on_top: false\ndefault_via_tented_on_bottom: false",
    anchor_position: { x: 2.0, y: 1.2 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.1,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_standalone",
    text: "Standalone pcb_via",
    anchor_position: { x: 2.0, y: 0.775 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.1,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_via",
    pcb_via_id: "board_open_via",
    subcircuit_id: "board_open",
    x: 2.0,
    y: 0.425,
    outer_diameter: 0.55,
    hole_diameter: 0.3,
    layers: ["top", "bottom"],
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_standalone_expected",
    text: "Expect: open hole, exposed copper ring",
    anchor_position: { x: 2.0, y: 0.025 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.0875,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_route",
    text: "pcb_trace.route via",
    anchor_position: { x: 2.0, y: -0.3 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.1,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "board_open_trace",
    subcircuit_id: "board_open",
    route: [
      {
        route_type: "wire",
        x: 1.375,
        y: -0.675,
        width: 0.075,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 2.0,
        y: -0.675,
        width: 0.075,
        layer: "top",
      },
      {
        route_type: "via",
        x: 2.0,
        y: -0.675,
        from_layer: "top",
        to_layer: "bottom",
      },
      {
        route_type: "wire",
        x: 2.0,
        y: -0.675,
        width: 0.075,
        layer: "bottom",
      },
      {
        route_type: "wire",
        x: 2.625,
        y: -0.675,
        width: 0.075,
        layer: "bottom",
      },
    ],
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_route_expected",
    text: "Expect: open hole, exposed copper ring",
    anchor_position: { x: 2.0, y: -1.075 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.0875,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "board_open_legend",
    text: "Pink: open drill",
    anchor_position: { x: 2.0, y: -1.3 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.0875,
    layer: "top",
    color: "white",
  },
]
