import type { AnyCircuitElement } from "circuit-json"

export const circuit: AnyCircuitElement[] = [
  {
    type: "pcb_board",
    pcb_board_id: "board",
    subcircuit_id: "board",
    center: { x: 0, y: 0 },
    width: 20,
    height: 12,
    thickness: 1.6,
    num_layers: 2,
    material: "fr4",
    min_via_hole_diameter: 1.2,
    min_via_pad_diameter: 2.2,
    default_via_plugged: true,
    default_via_tented_on_top: true,
    default_via_tented_on_bottom: false,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "view",
    text: "TOP VIEW - showSolderMask: true",
    anchor_position: { x: 0, y: 5.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.45,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "settings",
    text: "pcb_board.default_via_plugged: true\ndefault_via_tented_on_top: true\ndefault_via_tented_on_bottom: false",
    anchor_position: { x: 0, y: 3.9 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.37,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "pad_label",
    text: "pcb_smtpad + pcb_via",
    anchor_position: { x: -5, y: 1.8 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.34,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "silk_label",
    text: 'pcb_trace.route via +\npcb_silkscreen_text: "PB1"',
    anchor_position: { x: 5, y: 1.7 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.34,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_via",
    pcb_via_id: "pad_via",
    subcircuit_id: "board",
    x: -4.8,
    y: -0.5,
    outer_diameter: 2.2,
    hole_diameter: 1.2,
    layers: ["top", "bottom"],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "silk_trace",
    subcircuit_id: "board",
    route: [
      {
        route_type: "wire",
        x: 2.5,
        y: -0.5,
        width: 0.3,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 5,
        y: -0.5,
        width: 0.3,
        layer: "top",
      },
      {
        route_type: "via",
        x: 5,
        y: -0.5,
        from_layer: "top",
        to_layer: "bottom",
      },
      {
        route_type: "wire",
        x: 5,
        y: -0.5,
        width: 0.3,
        layer: "bottom",
      },
      {
        route_type: "wire",
        x: 7.5,
        y: -0.5,
        width: 0.3,
        layer: "bottom",
      },
    ],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pad_top",
    pcb_component_id: "component",
    shape: "rect",
    x: -6,
    y: -0.5,
    width: 2,
    height: 1.4,
    layer: "top",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "silk_top",
    pcb_component_id: "component",
    anchor_position: { x: 5, y: -0.5 },
    anchor_alignment: "center",
    text: "PB1",
    font: "tscircuit2024",
    font_size: 1.6,
    layer: "top",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pad_bottom",
    pcb_component_id: "component",
    shape: "rect",
    x: -6,
    y: -0.5,
    width: 2,
    height: 1.4,
    layer: "bottom",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "silk_bottom",
    pcb_component_id: "component",
    anchor_position: { x: 5, y: -0.5 },
    anchor_alignment: "center",
    text: "PB1",
    font: "tscircuit2024",
    font_size: 1.6,
    layer: "bottom",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "pad_expected",
    text: "Expect: pad opening stays exposed.\nPlug remains in the hole.",
    anchor_position: { x: -5, y: -2.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.32,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "silk_expected",
    text: 'Expect: "PB1" stays visible\nover the plugged hole.',
    anchor_position: { x: 5, y: -2.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.32,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "legend",
    text: "Tan: plugging material (not copper capping).\nTenting covers copper only where there is no pad opening.",
    anchor_position: { x: 0, y: -4.6 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.33,
    layer: "top",
    color: "white",
  },
]
