import type { AnyCircuitElement } from "circuit-json"

export const circuit: AnyCircuitElement[] = [
  {
    type: "pcb_board",
    pcb_board_id: "board",
    center: {
      x: 0,
      y: -0.8,
    },
    width: 24,
    height: 10,
    thickness: 1.6,
    num_layers: 2,
    material: "fr4",
    default_via_tented_on_top: true,
    default_via_tented_on_bottom: false,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "title",
    text: "pcb_board\ndefault_via_tented_on_top: true\ndefault_via_tented_on_bottom: false",
    anchor_position: {
      x: 0,
      y: 3.4,
    },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "tented_label",
    text: "Explicit tenting\ntented_on_top: true\ntented_on_bottom: true",
    anchor_position: {
      x: -8,
      y: 1.4,
    },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.38,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "exposed_label",
    text: "Explicit exposure\ntented_on_top: false\ntented_on_bottom: false",
    anchor_position: {
      x: 0,
      y: 1.4,
    },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.38,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "inherited_label",
    text: "Inherit board defaults\ntented_on_top: unset\ntented_on_bottom: unset",
    anchor_position: {
      x: 8,
      y: 1.4,
    },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.38,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "legend",
    text: 'pcb_silkscreen_text: "PB1" overlaps each pcb_via\nTented: text stays intact. Exposed: via interrupts text.',
    anchor_position: {
      x: 0,
      y: -3.3,
    },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.38,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_via",
    pcb_via_id: "tented",
    x: -8,
    y: -0.8,
    outer_diameter: 1.8,
    hole_diameter: 0.8,
    layers: ["top", "bottom"],
    tented_on_top: true,
    tented_on_bottom: true,
  },
  {
    type: "pcb_via",
    pcb_via_id: "exposed",
    x: 0,
    y: -0.8,
    outer_diameter: 1.8,
    hole_diameter: 0.8,
    layers: ["top", "bottom"],
    tented_on_top: false,
    tented_on_bottom: false,
  },
  {
    type: "pcb_via",
    pcb_via_id: "inherited",
    x: 8,
    y: -0.8,
    outer_diameter: 1.8,
    hole_diameter: 0.8,
    layers: ["top", "bottom"],
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "top_tented",
    pcb_component_id: "component",
    anchor_position: { x: -8, y: -0.8 },
    anchor_alignment: "center",
    text: "PB1",
    font: "tscircuit2024",
    font_size: 1.6,
    layer: "top",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "top_exposed",
    pcb_component_id: "component",
    anchor_position: { x: 0, y: -0.8 },
    anchor_alignment: "center",
    text: "PB1",
    font: "tscircuit2024",
    font_size: 1.6,
    layer: "top",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "top_inherited",
    pcb_component_id: "component",
    anchor_position: { x: 8, y: -0.8 },
    anchor_alignment: "center",
    text: "PB1",
    font: "tscircuit2024",
    font_size: 1.6,
    layer: "top",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "bottom_tented",
    pcb_component_id: "component",
    anchor_position: { x: -8, y: -0.8 },
    anchor_alignment: "center",
    text: "PB1",
    font: "tscircuit2024",
    font_size: 1.6,
    layer: "bottom",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "bottom_exposed",
    pcb_component_id: "component",
    anchor_position: { x: 0, y: -0.8 },
    anchor_alignment: "center",
    text: "PB1",
    font: "tscircuit2024",
    font_size: 1.6,
    layer: "bottom",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "bottom_inherited",
    pcb_component_id: "component",
    anchor_position: { x: 8, y: -0.8 },
    anchor_alignment: "center",
    text: "PB1",
    font: "tscircuit2024",
    font_size: 1.6,
    layer: "bottom",
  },
]
