import type { AnyCircuitElement } from "circuit-json"

export const circuit: AnyCircuitElement[] = [
  {
    type: "pcb_board",
    pcb_board_id: "board",
    subcircuit_id: "board",
    center: { x: 0.0, y: 0.0 },
    width: 5.0,
    height: 3.0,
    thickness: 1.6,
    num_layers: 2,
    material: "fr4",
    min_via_hole_diameter: 0.3,
    min_via_pad_diameter: 0.55,
    default_via_plugged: true,
    default_via_tented_on_top: true,
    default_via_tented_on_bottom: false,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "view",
    text: "TOP VIEW - showSolderMask: true",
    anchor_position: { x: 0.0, y: 1.375 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.1125,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "settings",
    text: "pcb_board.default_via_plugged: true\ndefault_via_tented_on_top: true\ndefault_via_tented_on_bottom: false",
    anchor_position: { x: 0.0, y: 0.975 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.0925,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "pad_label",
    text: "pcb_smtpad + pcb_via",
    anchor_position: { x: -1.25, y: 0.45 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.085,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "silk_label",
    text: 'pcb_trace.route via + pcb_silkscreen_text: "PB1"\ntented_on_bottom: true',
    anchor_position: { x: 1.25, y: 0.425 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.0725,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_via",
    pcb_via_id: "pad_via",
    subcircuit_id: "board",
    x: -1.2,
    y: -0.125,
    outer_diameter: 0.55,
    hole_diameter: 0.3,
    layers: ["top", "bottom"],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "silk_trace",
    subcircuit_id: "board",
    route: [
      {
        route_type: "wire",
        x: 0.625,
        y: -0.125,
        width: 0.075,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 1.25,
        y: -0.125,
        width: 0.075,
        layer: "top",
      },
      {
        route_type: "via",
        x: 1.25,
        y: -0.125,
        from_layer: "top",
        to_layer: "bottom",
        tented_on_bottom: true,
      },
      {
        route_type: "wire",
        x: 1.25,
        y: -0.125,
        width: 0.075,
        layer: "bottom",
      },
      {
        route_type: "wire",
        x: 1.875,
        y: -0.125,
        width: 0.075,
        layer: "bottom",
      },
    ],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pad_top",
    pcb_component_id: "component",
    shape: "rect",
    x: -1.5,
    y: -0.125,
    width: 0.5,
    height: 0.35,
    layer: "top",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "silk_top",
    pcb_component_id: "component",
    anchor_position: { x: 1.25, y: -0.125 },
    anchor_alignment: "center",
    text: "PB1",
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pad_bottom",
    pcb_component_id: "component",
    shape: "rect",
    x: -1.5,
    y: -0.125,
    width: 0.5,
    height: 0.35,
    layer: "bottom",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "silk_bottom",
    pcb_component_id: "component",
    anchor_position: { x: 1.25, y: -0.125 },
    anchor_alignment: "center",
    text: "PB1",
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "bottom",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "pad_expected",
    text: "Expect: pad opening stays exposed.\nPlug remains in the hole.",
    anchor_position: { x: -1.25, y: -0.625 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.08,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "silk_expected",
    text: 'Expect: "PB1" stays visible\nover the plugged hole.',
    anchor_position: { x: 1.25, y: -0.625 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.08,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "legend",
    text: "Ink plug: no copper cap. Pad overlap is a renderer stress case,\nnot JLCPCB's ink-plug manufacturing process.",
    anchor_position: { x: 0.0, y: -1.15 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.075,
    layer: "top",
    color: "white",
  },
]
