import type { AnyCircuitElement } from "circuit-json"

export const circuit: AnyCircuitElement[] = [
  {
    type: "pcb_board",
    pcb_board_id: "board",
    center: {
      x: 0,
      y: 0,
    },
    width: 12,
    height: 7,
    thickness: 1.6,
    num_layers: 2,
    material: "fr4",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "title",
    text: "Both pcb_via elements:\ntented_on_top: true\ntented_on_bottom: true",
    anchor_position: {
      x: 0,
      y: 2.55,
    },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.3,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pad_top",
    pcb_component_id: "component",
    shape: "rect",
    x: 1,
    y: -0.5,
    width: 2,
    height: 1.2,
    layer: "top",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pad_bottom",
    pcb_component_id: "component",
    shape: "rect",
    x: 1,
    y: -0.5,
    width: 2,
    height: 1.2,
    layer: "bottom",
  },
  {
    type: "pcb_via",
    pcb_via_id: "overlapping_via",
    x: 2.1,
    y: -0.5,
    outer_diameter: 1,
    hole_diameter: 0.4,
    layers: ["top", "bottom"],
    tented_on_top: true,
    tented_on_bottom: true,
  },
  {
    type: "pcb_via",
    pcb_via_id: "separate_via",
    x: -3.5,
    y: -0.5,
    outer_diameter: 1,
    hole_diameter: 0.4,
    layers: ["top", "bottom"],
    tented_on_top: true,
    tented_on_bottom: true,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "control_label",
    text: "pcb_via\nNo pad overlap",
    anchor_position: { x: -3.5, y: 1 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.25,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "overlap_label",
    text: "pcb_smtpad + pcb_via\nOverlapping pad edge",
    anchor_position: { x: 1.5, y: 1 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.25,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "control_expectation",
    text: "Expected:\nFully tented",
    anchor_position: { x: -3.5, y: -1.7 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.25,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "overlap_expectation",
    text: "Expected:\nPad opening stays exposed\nTenting ends at pad edge",
    anchor_position: { x: 1.5, y: -1.7 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.25,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "drill_legend",
    text: "Pink: drill exposed within the pad opening",
    anchor_position: { x: 0, y: -2.8 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 0.24,
    layer: "top",
    color: "white",
  },
]
